### ISSUE TITLE
Still in development?

### ISSUE THREAD

**Issue by owenselles** [Morganb816/Reddit-Uploader#1]
Hey there,

Are you still working on this or is it discontinued?

**Comment by Morganb816** [comment]
Hey Owen,
   Yes this is still in development I’ve just been busy with school and work but I should start making progress again tomorrow. If you would like to work on it let me know and I can get things better suited for multiple developers.
Thanks for reaching out!
Morgan

**Comment by owenselles** [comment]
ah thanks for the reply.
Do you have discord so i can contact you?

**Comment by Morganb816** [comment]
Morgan#4066
Feel free!

**Comment by Morganb816** [comment]
Contacted. Closing Issue.
